<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMzzsuux\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMzzsuux/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMzzsuux.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMzzsuux\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMzzsuux\appProdProjectContainer([
    'container.build_hash' => 'Mzzsuux',
    'container.build_id' => '00022d7c',
    'container.build_time' => 1656049989,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMzzsuux');
